### ISSUE TITLE
Storage Accounts fail with unparsed XML

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#257]
Understand & handle the following error in storage accounts:

```
22:04:55.744Z ERROR Local: Step "Storage Accounts" failed to complete due to error. (errorCode="UNEXPECTED_ERROR", errorId="472281fb-6ad1-4607-978c-fea4012372c4", reason="Unexpected error occurred executing integration! Please contact us in Slack or at https://support.jupiterone.io if the problem continues to occur.") (stepId=rm-storage-resources, errorId=472281fb-6ad1-4607-978c-fea4012372c4)
  RestError: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿<?xml version="1.0" encoding="utf-8"?>
  <StorageServiceProperties><Cors/><DeleteRetentionPolicy><Enabled>false</Enabled></DeleteRetentionPolicy></StorageServiceProperties>.
      at new RestError (/home/nick/projects/github/graph-azure/node_modules/@azure/storage-blob/node_modules/@azure/core-http/dist/index.js:2359:28)
      at errorHandler (/home/nick/projects/github/graph-azure/node_modules/@azure/storage-blob/node_modules/@azure/core-http/dist/index.js:3288:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ndowmon** [comment]
This is fixed in https://github.com/JupiterOne/graph-azure/pull/280
